buffer_destroy(global.bufId)
buffer_destroy(global.udpBufId)
ds_list_destroy(global.__FUCK_GAMEMAKER_LIST__)
ds_map_destroy(global.__ns_cmd_handler_map)
ds_map_destroy(global.__ns_event_handler_map)
ds_map_destroy(global.__ns_wait_handler_map)
_json_free()
